/*
public/portworx/pds/restore/apiv1/restore.proto

Testing RestoreServiceAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package restore

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/portworx/pds-api-go-client/unifiedcp/v2alpha2/clients/restore"
)

func Test_restore_RestoreServiceAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test RestoreServiceAPIService RestoreServiceCreateRestore", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var namespaceId string

		resp, httpRes, err := apiClient.RestoreServiceAPI.RestoreServiceCreateRestore(context.Background(), namespaceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RestoreServiceAPIService RestoreServiceDeleteRestore", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.RestoreServiceAPI.RestoreServiceDeleteRestore(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RestoreServiceAPIService RestoreServiceGetRestore", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.RestoreServiceAPI.RestoreServiceGetRestore(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RestoreServiceAPIService RestoreServiceListRestores", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.RestoreServiceAPI.RestoreServiceListRestores(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RestoreServiceAPIService RestoreServiceRecreateRestore", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.RestoreServiceAPI.RestoreServiceRecreateRestore(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
