/*
public/portworx/pds/copilot/apiv1/copilot.proto

Testing CopilotServiceAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package copilot

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/portworx/pds-api-go-client/unifiedcp/v2alpha2/clients/copilot"
)

func Test_copilot_CopilotServiceAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test CopilotServiceAPIService CopilotServiceSearchQuery", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CopilotServiceAPI.CopilotServiceSearchQuery(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
