/*
public/portworx/pds/tasks/apiv1/tasks.proto

Testing RestoreServiceAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package pdsclient

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_pdsclient_RestoreServiceAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test RestoreServiceAPIService RestoreServiceCreateRestore", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var namespaceId string

		resp, httpRes, err := apiClient.RestoreServiceAPI.RestoreServiceCreateRestore(context.Background(), namespaceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RestoreServiceAPIService RestoreServiceDeleteRestore", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.RestoreServiceAPI.RestoreServiceDeleteRestore(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RestoreServiceAPIService RestoreServiceGetRestore", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.RestoreServiceAPI.RestoreServiceGetRestore(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RestoreServiceAPIService RestoreServiceListRestores", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.RestoreServiceAPI.RestoreServiceListRestores(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RestoreServiceAPIService RestoreServiceRecreateRestore", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.RestoreServiceAPI.RestoreServiceRecreateRestore(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
