/*
public/portworx/pds/tasks/apiv1/tasks.proto

Testing BackupConfigServiceAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package pdsclient

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_pdsclient_BackupConfigServiceAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test BackupConfigServiceAPIService BackupConfigServiceCreateBackupConfig", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string

		resp, httpRes, err := apiClient.BackupConfigServiceAPI.BackupConfigServiceCreateBackupConfig(context.Background(), projectId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BackupConfigServiceAPIService BackupConfigServiceDeleteBackupConfig", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.BackupConfigServiceAPI.BackupConfigServiceDeleteBackupConfig(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BackupConfigServiceAPIService BackupConfigServiceGetBackupConfig", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.BackupConfigServiceAPI.BackupConfigServiceGetBackupConfig(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BackupConfigServiceAPIService BackupConfigServiceListBackupConfigs", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.BackupConfigServiceAPI.BackupConfigServiceListBackupConfigs(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BackupConfigServiceAPIService BackupConfigServiceUpdateBackupConfig", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var backupConfigMetaUid string

		resp, httpRes, err := apiClient.BackupConfigServiceAPI.BackupConfigServiceUpdateBackupConfig(context.Background(), backupConfigMetaUid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
