/*
public/portworx/pds/tasks/apiv1/tasks.proto

Testing CopilotServiceAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package pdsclient

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_pdsclient_CopilotServiceAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test CopilotServiceAPIService CopilotServiceSearchQuery", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CopilotServiceAPI.CopilotServiceSearchQuery(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
