/*
public/portworx/pds/tasks/apiv1/tasks.proto

Testing DeploymentEventServiceAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package pdsclient

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_pdsclient_DeploymentEventServiceAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DeploymentEventServiceAPIService DeploymentEventServiceListDeploymentEvents", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var deploymentId string

		resp, httpRes, err := apiClient.DeploymentEventServiceAPI.DeploymentEventServiceListDeploymentEvents(context.Background(), deploymentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
