/*
PDS API

Portworx Data Services API Server

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pds

import (
	"encoding/json"
)

// checks if the ControllersDeploymentTargetCredentialsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ControllersDeploymentTargetCredentialsResponse{}

// ControllersDeploymentTargetCredentialsResponse struct for ControllersDeploymentTargetCredentialsResponse
type ControllersDeploymentTargetCredentialsResponse struct {
	TeleportCaPin *string `json:"teleport_ca_pin,omitempty"`
	TeleportJoinToken *string `json:"teleport_join_token,omitempty"`
	TeleportProxyAddr *string `json:"teleport_proxy_addr,omitempty"`
}

// NewControllersDeploymentTargetCredentialsResponse instantiates a new ControllersDeploymentTargetCredentialsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewControllersDeploymentTargetCredentialsResponse() *ControllersDeploymentTargetCredentialsResponse {
	this := ControllersDeploymentTargetCredentialsResponse{}
	return &this
}

// NewControllersDeploymentTargetCredentialsResponseWithDefaults instantiates a new ControllersDeploymentTargetCredentialsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewControllersDeploymentTargetCredentialsResponseWithDefaults() *ControllersDeploymentTargetCredentialsResponse {
	this := ControllersDeploymentTargetCredentialsResponse{}
	return &this
}

// GetTeleportCaPin returns the TeleportCaPin field value if set, zero value otherwise.
func (o *ControllersDeploymentTargetCredentialsResponse) GetTeleportCaPin() string {
	if o == nil || IsNil(o.TeleportCaPin) {
		var ret string
		return ret
	}
	return *o.TeleportCaPin
}

// GetTeleportCaPinOk returns a tuple with the TeleportCaPin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ControllersDeploymentTargetCredentialsResponse) GetTeleportCaPinOk() (*string, bool) {
	if o == nil || IsNil(o.TeleportCaPin) {
		return nil, false
	}
	return o.TeleportCaPin, true
}

// HasTeleportCaPin returns a boolean if a field has been set.
func (o *ControllersDeploymentTargetCredentialsResponse) HasTeleportCaPin() bool {
	if o != nil && !IsNil(o.TeleportCaPin) {
		return true
	}

	return false
}

// SetTeleportCaPin gets a reference to the given string and assigns it to the TeleportCaPin field.
func (o *ControllersDeploymentTargetCredentialsResponse) SetTeleportCaPin(v string) {
	o.TeleportCaPin = &v
}

// GetTeleportJoinToken returns the TeleportJoinToken field value if set, zero value otherwise.
func (o *ControllersDeploymentTargetCredentialsResponse) GetTeleportJoinToken() string {
	if o == nil || IsNil(o.TeleportJoinToken) {
		var ret string
		return ret
	}
	return *o.TeleportJoinToken
}

// GetTeleportJoinTokenOk returns a tuple with the TeleportJoinToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ControllersDeploymentTargetCredentialsResponse) GetTeleportJoinTokenOk() (*string, bool) {
	if o == nil || IsNil(o.TeleportJoinToken) {
		return nil, false
	}
	return o.TeleportJoinToken, true
}

// HasTeleportJoinToken returns a boolean if a field has been set.
func (o *ControllersDeploymentTargetCredentialsResponse) HasTeleportJoinToken() bool {
	if o != nil && !IsNil(o.TeleportJoinToken) {
		return true
	}

	return false
}

// SetTeleportJoinToken gets a reference to the given string and assigns it to the TeleportJoinToken field.
func (o *ControllersDeploymentTargetCredentialsResponse) SetTeleportJoinToken(v string) {
	o.TeleportJoinToken = &v
}

// GetTeleportProxyAddr returns the TeleportProxyAddr field value if set, zero value otherwise.
func (o *ControllersDeploymentTargetCredentialsResponse) GetTeleportProxyAddr() string {
	if o == nil || IsNil(o.TeleportProxyAddr) {
		var ret string
		return ret
	}
	return *o.TeleportProxyAddr
}

// GetTeleportProxyAddrOk returns a tuple with the TeleportProxyAddr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ControllersDeploymentTargetCredentialsResponse) GetTeleportProxyAddrOk() (*string, bool) {
	if o == nil || IsNil(o.TeleportProxyAddr) {
		return nil, false
	}
	return o.TeleportProxyAddr, true
}

// HasTeleportProxyAddr returns a boolean if a field has been set.
func (o *ControllersDeploymentTargetCredentialsResponse) HasTeleportProxyAddr() bool {
	if o != nil && !IsNil(o.TeleportProxyAddr) {
		return true
	}

	return false
}

// SetTeleportProxyAddr gets a reference to the given string and assigns it to the TeleportProxyAddr field.
func (o *ControllersDeploymentTargetCredentialsResponse) SetTeleportProxyAddr(v string) {
	o.TeleportProxyAddr = &v
}

func (o ControllersDeploymentTargetCredentialsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ControllersDeploymentTargetCredentialsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TeleportCaPin) {
		toSerialize["teleport_ca_pin"] = o.TeleportCaPin
	}
	if !IsNil(o.TeleportJoinToken) {
		toSerialize["teleport_join_token"] = o.TeleportJoinToken
	}
	if !IsNil(o.TeleportProxyAddr) {
		toSerialize["teleport_proxy_addr"] = o.TeleportProxyAddr
	}
	return toSerialize, nil
}

type NullableControllersDeploymentTargetCredentialsResponse struct {
	value *ControllersDeploymentTargetCredentialsResponse
	isSet bool
}

func (v NullableControllersDeploymentTargetCredentialsResponse) Get() *ControllersDeploymentTargetCredentialsResponse {
	return v.value
}

func (v *NullableControllersDeploymentTargetCredentialsResponse) Set(val *ControllersDeploymentTargetCredentialsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableControllersDeploymentTargetCredentialsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableControllersDeploymentTargetCredentialsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableControllersDeploymentTargetCredentialsResponse(val *ControllersDeploymentTargetCredentialsResponse) *NullableControllersDeploymentTargetCredentialsResponse {
	return &NullableControllersDeploymentTargetCredentialsResponse{value: val, isSet: true}
}

func (v NullableControllersDeploymentTargetCredentialsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableControllersDeploymentTargetCredentialsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


