/*
PDS API

Portworx Data Services API Server

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pds

import (
	"encoding/json"
)

// checks if the ControllersCreateApplicationConfigurationTemplateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ControllersCreateApplicationConfigurationTemplateRequest{}

// ControllersCreateApplicationConfigurationTemplateRequest struct for ControllersCreateApplicationConfigurationTemplateRequest
type ControllersCreateApplicationConfigurationTemplateRequest struct {
	ConfigItems []ModelsConfigItem `json:"config_items,omitempty"`
	DataServiceId *string `json:"data_service_id,omitempty"`
	// See models.ApplicationConfigurationTemplate for more information.
	Name *string `json:"name,omitempty"`
}

// NewControllersCreateApplicationConfigurationTemplateRequest instantiates a new ControllersCreateApplicationConfigurationTemplateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewControllersCreateApplicationConfigurationTemplateRequest() *ControllersCreateApplicationConfigurationTemplateRequest {
	this := ControllersCreateApplicationConfigurationTemplateRequest{}
	return &this
}

// NewControllersCreateApplicationConfigurationTemplateRequestWithDefaults instantiates a new ControllersCreateApplicationConfigurationTemplateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewControllersCreateApplicationConfigurationTemplateRequestWithDefaults() *ControllersCreateApplicationConfigurationTemplateRequest {
	this := ControllersCreateApplicationConfigurationTemplateRequest{}
	return &this
}

// GetConfigItems returns the ConfigItems field value if set, zero value otherwise.
func (o *ControllersCreateApplicationConfigurationTemplateRequest) GetConfigItems() []ModelsConfigItem {
	if o == nil || IsNil(o.ConfigItems) {
		var ret []ModelsConfigItem
		return ret
	}
	return o.ConfigItems
}

// GetConfigItemsOk returns a tuple with the ConfigItems field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ControllersCreateApplicationConfigurationTemplateRequest) GetConfigItemsOk() ([]ModelsConfigItem, bool) {
	if o == nil || IsNil(o.ConfigItems) {
		return nil, false
	}
	return o.ConfigItems, true
}

// HasConfigItems returns a boolean if a field has been set.
func (o *ControllersCreateApplicationConfigurationTemplateRequest) HasConfigItems() bool {
	if o != nil && !IsNil(o.ConfigItems) {
		return true
	}

	return false
}

// SetConfigItems gets a reference to the given []ModelsConfigItem and assigns it to the ConfigItems field.
func (o *ControllersCreateApplicationConfigurationTemplateRequest) SetConfigItems(v []ModelsConfigItem) {
	o.ConfigItems = v
}

// GetDataServiceId returns the DataServiceId field value if set, zero value otherwise.
func (o *ControllersCreateApplicationConfigurationTemplateRequest) GetDataServiceId() string {
	if o == nil || IsNil(o.DataServiceId) {
		var ret string
		return ret
	}
	return *o.DataServiceId
}

// GetDataServiceIdOk returns a tuple with the DataServiceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ControllersCreateApplicationConfigurationTemplateRequest) GetDataServiceIdOk() (*string, bool) {
	if o == nil || IsNil(o.DataServiceId) {
		return nil, false
	}
	return o.DataServiceId, true
}

// HasDataServiceId returns a boolean if a field has been set.
func (o *ControllersCreateApplicationConfigurationTemplateRequest) HasDataServiceId() bool {
	if o != nil && !IsNil(o.DataServiceId) {
		return true
	}

	return false
}

// SetDataServiceId gets a reference to the given string and assigns it to the DataServiceId field.
func (o *ControllersCreateApplicationConfigurationTemplateRequest) SetDataServiceId(v string) {
	o.DataServiceId = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ControllersCreateApplicationConfigurationTemplateRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ControllersCreateApplicationConfigurationTemplateRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ControllersCreateApplicationConfigurationTemplateRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ControllersCreateApplicationConfigurationTemplateRequest) SetName(v string) {
	o.Name = &v
}

func (o ControllersCreateApplicationConfigurationTemplateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ControllersCreateApplicationConfigurationTemplateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ConfigItems) {
		toSerialize["config_items"] = o.ConfigItems
	}
	if !IsNil(o.DataServiceId) {
		toSerialize["data_service_id"] = o.DataServiceId
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableControllersCreateApplicationConfigurationTemplateRequest struct {
	value *ControllersCreateApplicationConfigurationTemplateRequest
	isSet bool
}

func (v NullableControllersCreateApplicationConfigurationTemplateRequest) Get() *ControllersCreateApplicationConfigurationTemplateRequest {
	return v.value
}

func (v *NullableControllersCreateApplicationConfigurationTemplateRequest) Set(val *ControllersCreateApplicationConfigurationTemplateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableControllersCreateApplicationConfigurationTemplateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableControllersCreateApplicationConfigurationTemplateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableControllersCreateApplicationConfigurationTemplateRequest(val *ControllersCreateApplicationConfigurationTemplateRequest) *NullableControllersCreateApplicationConfigurationTemplateRequest {
	return &NullableControllersCreateApplicationConfigurationTemplateRequest{value: val, isSet: true}
}

func (v NullableControllersCreateApplicationConfigurationTemplateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableControllersCreateApplicationConfigurationTemplateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


