/*
PDS API

Portworx Data Services API Server

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pds

import (
	"encoding/json"
)

// checks if the ModelsBackupJob type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsBackupJob{}

// ModelsBackupJob struct for ModelsBackupJob
type ModelsBackupJob struct {
	Backup *ModelsBackup `json:"backup,omitempty"`
	// BackupID which backup created the snapshot (nullable).
	BackupId *string `json:"backup_id,omitempty"`
	// BackupSpecJSON is the specification of the Backup in JSON format at the time the snapshot was taken.
	BackupSpec []int32 `json:"backup_spec,omitempty"`
	// CloudCredentialName credentials to access snapshot.
	CloudCredentialName *string `json:"cloud_credential_name,omitempty"`
	// CloudSnapID snapshot of the backup volume.
	CloudSnapId *string `json:"cloud_snap_id,omitempty"`
	// CompletionStatus of the backup job.
	CompletionStatus *string `json:"completion_status,omitempty"`
	CompletionTime *string `json:"completion_time,omitempty"`
	// CreatedAt is autogenerated on creation
	CreatedAt *string `json:"created_at,omitempty"`
	// BackupSpecJSON is the specification of the Backup in JSON format at the time the snapshot was taken.
	DataServiceSpec []int32 `json:"data_service_spec,omitempty"`
	Deployment *ModelsDeployment `json:"deployment,omitempty"`
	// DeploymentID which deployment was backed up (nullable).
	DeploymentId *string `json:"deployment_id,omitempty"`
	ErrorCode *string `json:"error_code,omitempty"`
	ErrorMessage *string `json:"error_message,omitempty"`
	// FileSize of the CloudSnap image.
	FileSize *int32 `json:"file_size,omitempty"`
	// ID is auto generated on creation
	Id *string `json:"id,omitempty"`
	// Name shown in UI.
	Name *string `json:"name,omitempty"`
	Project *ModelsProject `json:"project,omitempty"`
	// ProjectID which created the snapshot (required).
	ProjectId *string `json:"project_id,omitempty"`
	StartTime *string `json:"start_time,omitempty"`
	// UpdatedAt is autogenerated on update
	UpdatedAt *string `json:"updated_at,omitempty"`
}

// NewModelsBackupJob instantiates a new ModelsBackupJob object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsBackupJob() *ModelsBackupJob {
	this := ModelsBackupJob{}
	return &this
}

// NewModelsBackupJobWithDefaults instantiates a new ModelsBackupJob object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsBackupJobWithDefaults() *ModelsBackupJob {
	this := ModelsBackupJob{}
	return &this
}

// GetBackup returns the Backup field value if set, zero value otherwise.
func (o *ModelsBackupJob) GetBackup() ModelsBackup {
	if o == nil || IsNil(o.Backup) {
		var ret ModelsBackup
		return ret
	}
	return *o.Backup
}

// GetBackupOk returns a tuple with the Backup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsBackupJob) GetBackupOk() (*ModelsBackup, bool) {
	if o == nil || IsNil(o.Backup) {
		return nil, false
	}
	return o.Backup, true
}

// HasBackup returns a boolean if a field has been set.
func (o *ModelsBackupJob) HasBackup() bool {
	if o != nil && !IsNil(o.Backup) {
		return true
	}

	return false
}

// SetBackup gets a reference to the given ModelsBackup and assigns it to the Backup field.
func (o *ModelsBackupJob) SetBackup(v ModelsBackup) {
	o.Backup = &v
}

// GetBackupId returns the BackupId field value if set, zero value otherwise.
func (o *ModelsBackupJob) GetBackupId() string {
	if o == nil || IsNil(o.BackupId) {
		var ret string
		return ret
	}
	return *o.BackupId
}

// GetBackupIdOk returns a tuple with the BackupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsBackupJob) GetBackupIdOk() (*string, bool) {
	if o == nil || IsNil(o.BackupId) {
		return nil, false
	}
	return o.BackupId, true
}

// HasBackupId returns a boolean if a field has been set.
func (o *ModelsBackupJob) HasBackupId() bool {
	if o != nil && !IsNil(o.BackupId) {
		return true
	}

	return false
}

// SetBackupId gets a reference to the given string and assigns it to the BackupId field.
func (o *ModelsBackupJob) SetBackupId(v string) {
	o.BackupId = &v
}

// GetBackupSpec returns the BackupSpec field value if set, zero value otherwise.
func (o *ModelsBackupJob) GetBackupSpec() []int32 {
	if o == nil || IsNil(o.BackupSpec) {
		var ret []int32
		return ret
	}
	return o.BackupSpec
}

// GetBackupSpecOk returns a tuple with the BackupSpec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsBackupJob) GetBackupSpecOk() ([]int32, bool) {
	if o == nil || IsNil(o.BackupSpec) {
		return nil, false
	}
	return o.BackupSpec, true
}

// HasBackupSpec returns a boolean if a field has been set.
func (o *ModelsBackupJob) HasBackupSpec() bool {
	if o != nil && !IsNil(o.BackupSpec) {
		return true
	}

	return false
}

// SetBackupSpec gets a reference to the given []int32 and assigns it to the BackupSpec field.
func (o *ModelsBackupJob) SetBackupSpec(v []int32) {
	o.BackupSpec = v
}

// GetCloudCredentialName returns the CloudCredentialName field value if set, zero value otherwise.
func (o *ModelsBackupJob) GetCloudCredentialName() string {
	if o == nil || IsNil(o.CloudCredentialName) {
		var ret string
		return ret
	}
	return *o.CloudCredentialName
}

// GetCloudCredentialNameOk returns a tuple with the CloudCredentialName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsBackupJob) GetCloudCredentialNameOk() (*string, bool) {
	if o == nil || IsNil(o.CloudCredentialName) {
		return nil, false
	}
	return o.CloudCredentialName, true
}

// HasCloudCredentialName returns a boolean if a field has been set.
func (o *ModelsBackupJob) HasCloudCredentialName() bool {
	if o != nil && !IsNil(o.CloudCredentialName) {
		return true
	}

	return false
}

// SetCloudCredentialName gets a reference to the given string and assigns it to the CloudCredentialName field.
func (o *ModelsBackupJob) SetCloudCredentialName(v string) {
	o.CloudCredentialName = &v
}

// GetCloudSnapId returns the CloudSnapId field value if set, zero value otherwise.
func (o *ModelsBackupJob) GetCloudSnapId() string {
	if o == nil || IsNil(o.CloudSnapId) {
		var ret string
		return ret
	}
	return *o.CloudSnapId
}

// GetCloudSnapIdOk returns a tuple with the CloudSnapId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsBackupJob) GetCloudSnapIdOk() (*string, bool) {
	if o == nil || IsNil(o.CloudSnapId) {
		return nil, false
	}
	return o.CloudSnapId, true
}

// HasCloudSnapId returns a boolean if a field has been set.
func (o *ModelsBackupJob) HasCloudSnapId() bool {
	if o != nil && !IsNil(o.CloudSnapId) {
		return true
	}

	return false
}

// SetCloudSnapId gets a reference to the given string and assigns it to the CloudSnapId field.
func (o *ModelsBackupJob) SetCloudSnapId(v string) {
	o.CloudSnapId = &v
}

// GetCompletionStatus returns the CompletionStatus field value if set, zero value otherwise.
func (o *ModelsBackupJob) GetCompletionStatus() string {
	if o == nil || IsNil(o.CompletionStatus) {
		var ret string
		return ret
	}
	return *o.CompletionStatus
}

// GetCompletionStatusOk returns a tuple with the CompletionStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsBackupJob) GetCompletionStatusOk() (*string, bool) {
	if o == nil || IsNil(o.CompletionStatus) {
		return nil, false
	}
	return o.CompletionStatus, true
}

// HasCompletionStatus returns a boolean if a field has been set.
func (o *ModelsBackupJob) HasCompletionStatus() bool {
	if o != nil && !IsNil(o.CompletionStatus) {
		return true
	}

	return false
}

// SetCompletionStatus gets a reference to the given string and assigns it to the CompletionStatus field.
func (o *ModelsBackupJob) SetCompletionStatus(v string) {
	o.CompletionStatus = &v
}

// GetCompletionTime returns the CompletionTime field value if set, zero value otherwise.
func (o *ModelsBackupJob) GetCompletionTime() string {
	if o == nil || IsNil(o.CompletionTime) {
		var ret string
		return ret
	}
	return *o.CompletionTime
}

// GetCompletionTimeOk returns a tuple with the CompletionTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsBackupJob) GetCompletionTimeOk() (*string, bool) {
	if o == nil || IsNil(o.CompletionTime) {
		return nil, false
	}
	return o.CompletionTime, true
}

// HasCompletionTime returns a boolean if a field has been set.
func (o *ModelsBackupJob) HasCompletionTime() bool {
	if o != nil && !IsNil(o.CompletionTime) {
		return true
	}

	return false
}

// SetCompletionTime gets a reference to the given string and assigns it to the CompletionTime field.
func (o *ModelsBackupJob) SetCompletionTime(v string) {
	o.CompletionTime = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ModelsBackupJob) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsBackupJob) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ModelsBackupJob) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *ModelsBackupJob) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetDataServiceSpec returns the DataServiceSpec field value if set, zero value otherwise.
func (o *ModelsBackupJob) GetDataServiceSpec() []int32 {
	if o == nil || IsNil(o.DataServiceSpec) {
		var ret []int32
		return ret
	}
	return o.DataServiceSpec
}

// GetDataServiceSpecOk returns a tuple with the DataServiceSpec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsBackupJob) GetDataServiceSpecOk() ([]int32, bool) {
	if o == nil || IsNil(o.DataServiceSpec) {
		return nil, false
	}
	return o.DataServiceSpec, true
}

// HasDataServiceSpec returns a boolean if a field has been set.
func (o *ModelsBackupJob) HasDataServiceSpec() bool {
	if o != nil && !IsNil(o.DataServiceSpec) {
		return true
	}

	return false
}

// SetDataServiceSpec gets a reference to the given []int32 and assigns it to the DataServiceSpec field.
func (o *ModelsBackupJob) SetDataServiceSpec(v []int32) {
	o.DataServiceSpec = v
}

// GetDeployment returns the Deployment field value if set, zero value otherwise.
func (o *ModelsBackupJob) GetDeployment() ModelsDeployment {
	if o == nil || IsNil(o.Deployment) {
		var ret ModelsDeployment
		return ret
	}
	return *o.Deployment
}

// GetDeploymentOk returns a tuple with the Deployment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsBackupJob) GetDeploymentOk() (*ModelsDeployment, bool) {
	if o == nil || IsNil(o.Deployment) {
		return nil, false
	}
	return o.Deployment, true
}

// HasDeployment returns a boolean if a field has been set.
func (o *ModelsBackupJob) HasDeployment() bool {
	if o != nil && !IsNil(o.Deployment) {
		return true
	}

	return false
}

// SetDeployment gets a reference to the given ModelsDeployment and assigns it to the Deployment field.
func (o *ModelsBackupJob) SetDeployment(v ModelsDeployment) {
	o.Deployment = &v
}

// GetDeploymentId returns the DeploymentId field value if set, zero value otherwise.
func (o *ModelsBackupJob) GetDeploymentId() string {
	if o == nil || IsNil(o.DeploymentId) {
		var ret string
		return ret
	}
	return *o.DeploymentId
}

// GetDeploymentIdOk returns a tuple with the DeploymentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsBackupJob) GetDeploymentIdOk() (*string, bool) {
	if o == nil || IsNil(o.DeploymentId) {
		return nil, false
	}
	return o.DeploymentId, true
}

// HasDeploymentId returns a boolean if a field has been set.
func (o *ModelsBackupJob) HasDeploymentId() bool {
	if o != nil && !IsNil(o.DeploymentId) {
		return true
	}

	return false
}

// SetDeploymentId gets a reference to the given string and assigns it to the DeploymentId field.
func (o *ModelsBackupJob) SetDeploymentId(v string) {
	o.DeploymentId = &v
}

// GetErrorCode returns the ErrorCode field value if set, zero value otherwise.
func (o *ModelsBackupJob) GetErrorCode() string {
	if o == nil || IsNil(o.ErrorCode) {
		var ret string
		return ret
	}
	return *o.ErrorCode
}

// GetErrorCodeOk returns a tuple with the ErrorCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsBackupJob) GetErrorCodeOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorCode) {
		return nil, false
	}
	return o.ErrorCode, true
}

// HasErrorCode returns a boolean if a field has been set.
func (o *ModelsBackupJob) HasErrorCode() bool {
	if o != nil && !IsNil(o.ErrorCode) {
		return true
	}

	return false
}

// SetErrorCode gets a reference to the given string and assigns it to the ErrorCode field.
func (o *ModelsBackupJob) SetErrorCode(v string) {
	o.ErrorCode = &v
}

// GetErrorMessage returns the ErrorMessage field value if set, zero value otherwise.
func (o *ModelsBackupJob) GetErrorMessage() string {
	if o == nil || IsNil(o.ErrorMessage) {
		var ret string
		return ret
	}
	return *o.ErrorMessage
}

// GetErrorMessageOk returns a tuple with the ErrorMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsBackupJob) GetErrorMessageOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorMessage) {
		return nil, false
	}
	return o.ErrorMessage, true
}

// HasErrorMessage returns a boolean if a field has been set.
func (o *ModelsBackupJob) HasErrorMessage() bool {
	if o != nil && !IsNil(o.ErrorMessage) {
		return true
	}

	return false
}

// SetErrorMessage gets a reference to the given string and assigns it to the ErrorMessage field.
func (o *ModelsBackupJob) SetErrorMessage(v string) {
	o.ErrorMessage = &v
}

// GetFileSize returns the FileSize field value if set, zero value otherwise.
func (o *ModelsBackupJob) GetFileSize() int32 {
	if o == nil || IsNil(o.FileSize) {
		var ret int32
		return ret
	}
	return *o.FileSize
}

// GetFileSizeOk returns a tuple with the FileSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsBackupJob) GetFileSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.FileSize) {
		return nil, false
	}
	return o.FileSize, true
}

// HasFileSize returns a boolean if a field has been set.
func (o *ModelsBackupJob) HasFileSize() bool {
	if o != nil && !IsNil(o.FileSize) {
		return true
	}

	return false
}

// SetFileSize gets a reference to the given int32 and assigns it to the FileSize field.
func (o *ModelsBackupJob) SetFileSize(v int32) {
	o.FileSize = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ModelsBackupJob) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsBackupJob) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ModelsBackupJob) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ModelsBackupJob) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ModelsBackupJob) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsBackupJob) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ModelsBackupJob) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ModelsBackupJob) SetName(v string) {
	o.Name = &v
}

// GetProject returns the Project field value if set, zero value otherwise.
func (o *ModelsBackupJob) GetProject() ModelsProject {
	if o == nil || IsNil(o.Project) {
		var ret ModelsProject
		return ret
	}
	return *o.Project
}

// GetProjectOk returns a tuple with the Project field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsBackupJob) GetProjectOk() (*ModelsProject, bool) {
	if o == nil || IsNil(o.Project) {
		return nil, false
	}
	return o.Project, true
}

// HasProject returns a boolean if a field has been set.
func (o *ModelsBackupJob) HasProject() bool {
	if o != nil && !IsNil(o.Project) {
		return true
	}

	return false
}

// SetProject gets a reference to the given ModelsProject and assigns it to the Project field.
func (o *ModelsBackupJob) SetProject(v ModelsProject) {
	o.Project = &v
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *ModelsBackupJob) GetProjectId() string {
	if o == nil || IsNil(o.ProjectId) {
		var ret string
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsBackupJob) GetProjectIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProjectId) {
		return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *ModelsBackupJob) HasProjectId() bool {
	if o != nil && !IsNil(o.ProjectId) {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given string and assigns it to the ProjectId field.
func (o *ModelsBackupJob) SetProjectId(v string) {
	o.ProjectId = &v
}

// GetStartTime returns the StartTime field value if set, zero value otherwise.
func (o *ModelsBackupJob) GetStartTime() string {
	if o == nil || IsNil(o.StartTime) {
		var ret string
		return ret
	}
	return *o.StartTime
}

// GetStartTimeOk returns a tuple with the StartTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsBackupJob) GetStartTimeOk() (*string, bool) {
	if o == nil || IsNil(o.StartTime) {
		return nil, false
	}
	return o.StartTime, true
}

// HasStartTime returns a boolean if a field has been set.
func (o *ModelsBackupJob) HasStartTime() bool {
	if o != nil && !IsNil(o.StartTime) {
		return true
	}

	return false
}

// SetStartTime gets a reference to the given string and assigns it to the StartTime field.
func (o *ModelsBackupJob) SetStartTime(v string) {
	o.StartTime = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *ModelsBackupJob) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsBackupJob) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *ModelsBackupJob) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *ModelsBackupJob) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

func (o ModelsBackupJob) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsBackupJob) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Backup) {
		toSerialize["backup"] = o.Backup
	}
	if !IsNil(o.BackupId) {
		toSerialize["backup_id"] = o.BackupId
	}
	if !IsNil(o.BackupSpec) {
		toSerialize["backup_spec"] = o.BackupSpec
	}
	if !IsNil(o.CloudCredentialName) {
		toSerialize["cloud_credential_name"] = o.CloudCredentialName
	}
	if !IsNil(o.CloudSnapId) {
		toSerialize["cloud_snap_id"] = o.CloudSnapId
	}
	if !IsNil(o.CompletionStatus) {
		toSerialize["completion_status"] = o.CompletionStatus
	}
	if !IsNil(o.CompletionTime) {
		toSerialize["completion_time"] = o.CompletionTime
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.DataServiceSpec) {
		toSerialize["data_service_spec"] = o.DataServiceSpec
	}
	if !IsNil(o.Deployment) {
		toSerialize["deployment"] = o.Deployment
	}
	if !IsNil(o.DeploymentId) {
		toSerialize["deployment_id"] = o.DeploymentId
	}
	if !IsNil(o.ErrorCode) {
		toSerialize["error_code"] = o.ErrorCode
	}
	if !IsNil(o.ErrorMessage) {
		toSerialize["error_message"] = o.ErrorMessage
	}
	if !IsNil(o.FileSize) {
		toSerialize["file_size"] = o.FileSize
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Project) {
		toSerialize["project"] = o.Project
	}
	if !IsNil(o.ProjectId) {
		toSerialize["project_id"] = o.ProjectId
	}
	if !IsNil(o.StartTime) {
		toSerialize["start_time"] = o.StartTime
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableModelsBackupJob struct {
	value *ModelsBackupJob
	isSet bool
}

func (v NullableModelsBackupJob) Get() *ModelsBackupJob {
	return v.value
}

func (v *NullableModelsBackupJob) Set(val *ModelsBackupJob) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsBackupJob) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsBackupJob) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsBackupJob(val *ModelsBackupJob) *NullableModelsBackupJob {
	return &NullableModelsBackupJob{value: val, isSet: true}
}

func (v NullableModelsBackupJob) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsBackupJob) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


