/*
PDS API

Portworx Data Services API Server

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pds

import (
	"encoding/json"
)

// ModelsApplicationConfigurationSample struct for ModelsApplicationConfigurationSample
type ModelsApplicationConfigurationSample struct {
	ConfigItems []ModelsConfigItem `json:"config_items,omitempty"`
	DataServiceId *string `json:"data_service_id,omitempty"`
	// Name of the template. Must be unique for a specific data service within the tenant scope.
	Name *string `json:"name,omitempty"`
}

// NewModelsApplicationConfigurationSample instantiates a new ModelsApplicationConfigurationSample object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsApplicationConfigurationSample() *ModelsApplicationConfigurationSample {
	this := ModelsApplicationConfigurationSample{}
	return &this
}

// NewModelsApplicationConfigurationSampleWithDefaults instantiates a new ModelsApplicationConfigurationSample object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsApplicationConfigurationSampleWithDefaults() *ModelsApplicationConfigurationSample {
	this := ModelsApplicationConfigurationSample{}
	return &this
}

// GetConfigItems returns the ConfigItems field value if set, zero value otherwise.
func (o *ModelsApplicationConfigurationSample) GetConfigItems() []ModelsConfigItem {
	if o == nil || o.ConfigItems == nil {
		var ret []ModelsConfigItem
		return ret
	}
	return o.ConfigItems
}

// GetConfigItemsOk returns a tuple with the ConfigItems field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsApplicationConfigurationSample) GetConfigItemsOk() ([]ModelsConfigItem, bool) {
	if o == nil || o.ConfigItems == nil {
		return nil, false
	}
	return o.ConfigItems, true
}

// HasConfigItems returns a boolean if a field has been set.
func (o *ModelsApplicationConfigurationSample) HasConfigItems() bool {
	if o != nil && o.ConfigItems != nil {
		return true
	}

	return false
}

// SetConfigItems gets a reference to the given []ModelsConfigItem and assigns it to the ConfigItems field.
func (o *ModelsApplicationConfigurationSample) SetConfigItems(v []ModelsConfigItem) {
	o.ConfigItems = v
}

// GetDataServiceId returns the DataServiceId field value if set, zero value otherwise.
func (o *ModelsApplicationConfigurationSample) GetDataServiceId() string {
	if o == nil || o.DataServiceId == nil {
		var ret string
		return ret
	}
	return *o.DataServiceId
}

// GetDataServiceIdOk returns a tuple with the DataServiceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsApplicationConfigurationSample) GetDataServiceIdOk() (*string, bool) {
	if o == nil || o.DataServiceId == nil {
		return nil, false
	}
	return o.DataServiceId, true
}

// HasDataServiceId returns a boolean if a field has been set.
func (o *ModelsApplicationConfigurationSample) HasDataServiceId() bool {
	if o != nil && o.DataServiceId != nil {
		return true
	}

	return false
}

// SetDataServiceId gets a reference to the given string and assigns it to the DataServiceId field.
func (o *ModelsApplicationConfigurationSample) SetDataServiceId(v string) {
	o.DataServiceId = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ModelsApplicationConfigurationSample) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsApplicationConfigurationSample) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ModelsApplicationConfigurationSample) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ModelsApplicationConfigurationSample) SetName(v string) {
	o.Name = &v
}

func (o ModelsApplicationConfigurationSample) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ConfigItems != nil {
		toSerialize["config_items"] = o.ConfigItems
	}
	if o.DataServiceId != nil {
		toSerialize["data_service_id"] = o.DataServiceId
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableModelsApplicationConfigurationSample struct {
	value *ModelsApplicationConfigurationSample
	isSet bool
}

func (v NullableModelsApplicationConfigurationSample) Get() *ModelsApplicationConfigurationSample {
	return v.value
}

func (v *NullableModelsApplicationConfigurationSample) Set(val *ModelsApplicationConfigurationSample) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsApplicationConfigurationSample) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsApplicationConfigurationSample) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsApplicationConfigurationSample(val *ModelsApplicationConfigurationSample) *NullableModelsApplicationConfigurationSample {
	return &NullableModelsApplicationConfigurationSample{value: val, isSet: true}
}

func (v NullableModelsApplicationConfigurationSample) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsApplicationConfigurationSample) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


