/*
PDS API

Portworx Data Services API Server

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pds

import (
	"encoding/json"
)

// RequestsPatchTenantRequest struct for RequestsPatchTenantRequest
type RequestsPatchTenantRequest struct {
	// Name of the Tenant. Must be unique within an Account.
	Name *string `json:"name,omitempty"`
}

// NewRequestsPatchTenantRequest instantiates a new RequestsPatchTenantRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestsPatchTenantRequest() *RequestsPatchTenantRequest {
	this := RequestsPatchTenantRequest{}
	return &this
}

// NewRequestsPatchTenantRequestWithDefaults instantiates a new RequestsPatchTenantRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestsPatchTenantRequestWithDefaults() *RequestsPatchTenantRequest {
	this := RequestsPatchTenantRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *RequestsPatchTenantRequest) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestsPatchTenantRequest) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *RequestsPatchTenantRequest) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *RequestsPatchTenantRequest) SetName(v string) {
	o.Name = &v
}

func (o RequestsPatchTenantRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableRequestsPatchTenantRequest struct {
	value *RequestsPatchTenantRequest
	isSet bool
}

func (v NullableRequestsPatchTenantRequest) Get() *RequestsPatchTenantRequest {
	return v.value
}

func (v *NullableRequestsPatchTenantRequest) Set(val *RequestsPatchTenantRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestsPatchTenantRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestsPatchTenantRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestsPatchTenantRequest(val *RequestsPatchTenantRequest) *NullableRequestsPatchTenantRequest {
	return &NullableRequestsPatchTenantRequest{value: val, isSet: true}
}

func (v NullableRequestsPatchTenantRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestsPatchTenantRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


