/*
PDS API

Portworx Data Services API Server

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pds

import (
	"encoding/json"
)

// checks if the ModelsConfigItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsConfigItem{}

// ModelsConfigItem struct for ModelsConfigItem
type ModelsConfigItem struct {
	// If true, user must fill the value for this configuration parameter when creating a new deployment.
	DeployTime *bool `json:"deploy_time,omitempty"`
	// Configuration key, transfers to the image's environment variable.
	Key *string `json:"key,omitempty"`
	// Configuration value.
	Value *string `json:"value,omitempty"`
}

// NewModelsConfigItem instantiates a new ModelsConfigItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsConfigItem() *ModelsConfigItem {
	this := ModelsConfigItem{}
	return &this
}

// NewModelsConfigItemWithDefaults instantiates a new ModelsConfigItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsConfigItemWithDefaults() *ModelsConfigItem {
	this := ModelsConfigItem{}
	return &this
}

// GetDeployTime returns the DeployTime field value if set, zero value otherwise.
func (o *ModelsConfigItem) GetDeployTime() bool {
	if o == nil || IsNil(o.DeployTime) {
		var ret bool
		return ret
	}
	return *o.DeployTime
}

// GetDeployTimeOk returns a tuple with the DeployTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsConfigItem) GetDeployTimeOk() (*bool, bool) {
	if o == nil || IsNil(o.DeployTime) {
		return nil, false
	}
	return o.DeployTime, true
}

// HasDeployTime returns a boolean if a field has been set.
func (o *ModelsConfigItem) HasDeployTime() bool {
	if o != nil && !IsNil(o.DeployTime) {
		return true
	}

	return false
}

// SetDeployTime gets a reference to the given bool and assigns it to the DeployTime field.
func (o *ModelsConfigItem) SetDeployTime(v bool) {
	o.DeployTime = &v
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *ModelsConfigItem) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsConfigItem) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *ModelsConfigItem) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *ModelsConfigItem) SetKey(v string) {
	o.Key = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *ModelsConfigItem) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsConfigItem) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *ModelsConfigItem) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *ModelsConfigItem) SetValue(v string) {
	o.Value = &v
}

func (o ModelsConfigItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsConfigItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DeployTime) {
		toSerialize["deploy_time"] = o.DeployTime
	}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableModelsConfigItem struct {
	value *ModelsConfigItem
	isSet bool
}

func (v NullableModelsConfigItem) Get() *ModelsConfigItem {
	return v.value
}

func (v *NullableModelsConfigItem) Set(val *ModelsConfigItem) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsConfigItem) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsConfigItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsConfigItem(val *ModelsConfigItem) *NullableModelsConfigItem {
	return &NullableModelsConfigItem{value: val, isSet: true}
}

func (v NullableModelsConfigItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsConfigItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


