/*
PDS API

Portworx Data Services API Server

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pds

import (
	"encoding/json"
)

// RequestsPatchProjectRequest struct for RequestsPatchProjectRequest
type RequestsPatchProjectRequest struct {
	// Name of the Project. Must be unique within a Tenant.
	Name *string `json:"name,omitempty"`
}

// NewRequestsPatchProjectRequest instantiates a new RequestsPatchProjectRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestsPatchProjectRequest() *RequestsPatchProjectRequest {
	this := RequestsPatchProjectRequest{}
	return &this
}

// NewRequestsPatchProjectRequestWithDefaults instantiates a new RequestsPatchProjectRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestsPatchProjectRequestWithDefaults() *RequestsPatchProjectRequest {
	this := RequestsPatchProjectRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *RequestsPatchProjectRequest) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestsPatchProjectRequest) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *RequestsPatchProjectRequest) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *RequestsPatchProjectRequest) SetName(v string) {
	o.Name = &v
}

func (o RequestsPatchProjectRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableRequestsPatchProjectRequest struct {
	value *RequestsPatchProjectRequest
	isSet bool
}

func (v NullableRequestsPatchProjectRequest) Get() *RequestsPatchProjectRequest {
	return v.value
}

func (v *NullableRequestsPatchProjectRequest) Set(val *RequestsPatchProjectRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestsPatchProjectRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestsPatchProjectRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestsPatchProjectRequest(val *RequestsPatchProjectRequest) *NullableRequestsPatchProjectRequest {
	return &NullableRequestsPatchProjectRequest{value: val, isSet: true}
}

func (v NullableRequestsPatchProjectRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestsPatchProjectRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


