/*
PDS API

Portworx Data Services API Server

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pds

import (
	"encoding/json"
)

// checks if the ServiceDeploymentResourceEvents type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceDeploymentResourceEvents{}

// ServiceDeploymentResourceEvents struct for ServiceDeploymentResourceEvents
type ServiceDeploymentResourceEvents struct {
	ResourceEvents []DeploymentsResourceEvents `json:"resourceEvents,omitempty"`
}

// NewServiceDeploymentResourceEvents instantiates a new ServiceDeploymentResourceEvents object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceDeploymentResourceEvents() *ServiceDeploymentResourceEvents {
	this := ServiceDeploymentResourceEvents{}
	return &this
}

// NewServiceDeploymentResourceEventsWithDefaults instantiates a new ServiceDeploymentResourceEvents object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceDeploymentResourceEventsWithDefaults() *ServiceDeploymentResourceEvents {
	this := ServiceDeploymentResourceEvents{}
	return &this
}

// GetResourceEvents returns the ResourceEvents field value if set, zero value otherwise.
func (o *ServiceDeploymentResourceEvents) GetResourceEvents() []DeploymentsResourceEvents {
	if o == nil || IsNil(o.ResourceEvents) {
		var ret []DeploymentsResourceEvents
		return ret
	}
	return o.ResourceEvents
}

// GetResourceEventsOk returns a tuple with the ResourceEvents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceDeploymentResourceEvents) GetResourceEventsOk() ([]DeploymentsResourceEvents, bool) {
	if o == nil || IsNil(o.ResourceEvents) {
		return nil, false
	}
	return o.ResourceEvents, true
}

// HasResourceEvents returns a boolean if a field has been set.
func (o *ServiceDeploymentResourceEvents) HasResourceEvents() bool {
	if o != nil && !IsNil(o.ResourceEvents) {
		return true
	}

	return false
}

// SetResourceEvents gets a reference to the given []DeploymentsResourceEvents and assigns it to the ResourceEvents field.
func (o *ServiceDeploymentResourceEvents) SetResourceEvents(v []DeploymentsResourceEvents) {
	o.ResourceEvents = v
}

func (o ServiceDeploymentResourceEvents) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceDeploymentResourceEvents) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ResourceEvents) {
		toSerialize["resourceEvents"] = o.ResourceEvents
	}
	return toSerialize, nil
}

type NullableServiceDeploymentResourceEvents struct {
	value *ServiceDeploymentResourceEvents
	isSet bool
}

func (v NullableServiceDeploymentResourceEvents) Get() *ServiceDeploymentResourceEvents {
	return v.value
}

func (v *NullableServiceDeploymentResourceEvents) Set(val *ServiceDeploymentResourceEvents) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceDeploymentResourceEvents) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceDeploymentResourceEvents) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceDeploymentResourceEvents(val *ServiceDeploymentResourceEvents) *NullableServiceDeploymentResourceEvents {
	return &NullableServiceDeploymentResourceEvents{value: val, isSet: true}
}

func (v NullableServiceDeploymentResourceEvents) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceDeploymentResourceEvents) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


