/*
PDS API

Portworx Data Services API Server

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pds

import (
	"encoding/json"
)

// RequestsDeploymentTargetIDArrayRequest struct for RequestsDeploymentTargetIDArrayRequest
type RequestsDeploymentTargetIDArrayRequest struct {
	DeploymentTargetIds []string `json:"deployment_target_ids,omitempty"`
}

// NewRequestsDeploymentTargetIDArrayRequest instantiates a new RequestsDeploymentTargetIDArrayRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestsDeploymentTargetIDArrayRequest() *RequestsDeploymentTargetIDArrayRequest {
	this := RequestsDeploymentTargetIDArrayRequest{}
	return &this
}

// NewRequestsDeploymentTargetIDArrayRequestWithDefaults instantiates a new RequestsDeploymentTargetIDArrayRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestsDeploymentTargetIDArrayRequestWithDefaults() *RequestsDeploymentTargetIDArrayRequest {
	this := RequestsDeploymentTargetIDArrayRequest{}
	return &this
}

// GetDeploymentTargetIds returns the DeploymentTargetIds field value if set, zero value otherwise.
func (o *RequestsDeploymentTargetIDArrayRequest) GetDeploymentTargetIds() []string {
	if o == nil || o.DeploymentTargetIds == nil {
		var ret []string
		return ret
	}
	return o.DeploymentTargetIds
}

// GetDeploymentTargetIdsOk returns a tuple with the DeploymentTargetIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestsDeploymentTargetIDArrayRequest) GetDeploymentTargetIdsOk() ([]string, bool) {
	if o == nil || o.DeploymentTargetIds == nil {
		return nil, false
	}
	return o.DeploymentTargetIds, true
}

// HasDeploymentTargetIds returns a boolean if a field has been set.
func (o *RequestsDeploymentTargetIDArrayRequest) HasDeploymentTargetIds() bool {
	if o != nil && o.DeploymentTargetIds != nil {
		return true
	}

	return false
}

// SetDeploymentTargetIds gets a reference to the given []string and assigns it to the DeploymentTargetIds field.
func (o *RequestsDeploymentTargetIDArrayRequest) SetDeploymentTargetIds(v []string) {
	o.DeploymentTargetIds = v
}

func (o RequestsDeploymentTargetIDArrayRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.DeploymentTargetIds != nil {
		toSerialize["deployment_target_ids"] = o.DeploymentTargetIds
	}
	return json.Marshal(toSerialize)
}

type NullableRequestsDeploymentTargetIDArrayRequest struct {
	value *RequestsDeploymentTargetIDArrayRequest
	isSet bool
}

func (v NullableRequestsDeploymentTargetIDArrayRequest) Get() *RequestsDeploymentTargetIDArrayRequest {
	return v.value
}

func (v *NullableRequestsDeploymentTargetIDArrayRequest) Set(val *RequestsDeploymentTargetIDArrayRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestsDeploymentTargetIDArrayRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestsDeploymentTargetIDArrayRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestsDeploymentTargetIDArrayRequest(val *RequestsDeploymentTargetIDArrayRequest) *NullableRequestsDeploymentTargetIDArrayRequest {
	return &NullableRequestsDeploymentTargetIDArrayRequest{value: val, isSet: true}
}

func (v NullableRequestsDeploymentTargetIDArrayRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestsDeploymentTargetIDArrayRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


