/*
PDS API

Portworx Data Services API Server

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pds

import (
	"encoding/json"
)

// checks if the DeploymentsCredentials type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeploymentsCredentials{}

// DeploymentsCredentials struct for DeploymentsCredentials
type DeploymentsCredentials struct {
	Password *string `json:"password,omitempty"`
}

// NewDeploymentsCredentials instantiates a new DeploymentsCredentials object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeploymentsCredentials() *DeploymentsCredentials {
	this := DeploymentsCredentials{}
	return &this
}

// NewDeploymentsCredentialsWithDefaults instantiates a new DeploymentsCredentials object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeploymentsCredentialsWithDefaults() *DeploymentsCredentials {
	this := DeploymentsCredentials{}
	return &this
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *DeploymentsCredentials) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentsCredentials) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *DeploymentsCredentials) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *DeploymentsCredentials) SetPassword(v string) {
	o.Password = &v
}

func (o DeploymentsCredentials) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeploymentsCredentials) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	return toSerialize, nil
}

type NullableDeploymentsCredentials struct {
	value *DeploymentsCredentials
	isSet bool
}

func (v NullableDeploymentsCredentials) Get() *DeploymentsCredentials {
	return v.value
}

func (v *NullableDeploymentsCredentials) Set(val *DeploymentsCredentials) {
	v.value = val
	v.isSet = true
}

func (v NullableDeploymentsCredentials) IsSet() bool {
	return v.isSet
}

func (v *NullableDeploymentsCredentials) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeploymentsCredentials(val *DeploymentsCredentials) *NullableDeploymentsCredentials {
	return &NullableDeploymentsCredentials{value: val, isSet: true}
}

func (v NullableDeploymentsCredentials) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeploymentsCredentials) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


