/*
PDS API

Portworx Data Services API Server

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pds

import (
	"encoding/json"
)

// checks if the ControllersWhoAmIResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ControllersWhoAmIResponse{}

// ControllersWhoAmIResponse struct for ControllersWhoAmIResponse
type ControllersWhoAmIResponse struct {
	ServiceAccount *ControllersWhoAmIServiceAccount `json:"service_account,omitempty"`
	User *ControllersWhoAmIUser `json:"user,omitempty"`
}

// NewControllersWhoAmIResponse instantiates a new ControllersWhoAmIResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewControllersWhoAmIResponse() *ControllersWhoAmIResponse {
	this := ControllersWhoAmIResponse{}
	return &this
}

// NewControllersWhoAmIResponseWithDefaults instantiates a new ControllersWhoAmIResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewControllersWhoAmIResponseWithDefaults() *ControllersWhoAmIResponse {
	this := ControllersWhoAmIResponse{}
	return &this
}

// GetServiceAccount returns the ServiceAccount field value if set, zero value otherwise.
func (o *ControllersWhoAmIResponse) GetServiceAccount() ControllersWhoAmIServiceAccount {
	if o == nil || IsNil(o.ServiceAccount) {
		var ret ControllersWhoAmIServiceAccount
		return ret
	}
	return *o.ServiceAccount
}

// GetServiceAccountOk returns a tuple with the ServiceAccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ControllersWhoAmIResponse) GetServiceAccountOk() (*ControllersWhoAmIServiceAccount, bool) {
	if o == nil || IsNil(o.ServiceAccount) {
		return nil, false
	}
	return o.ServiceAccount, true
}

// HasServiceAccount returns a boolean if a field has been set.
func (o *ControllersWhoAmIResponse) HasServiceAccount() bool {
	if o != nil && !IsNil(o.ServiceAccount) {
		return true
	}

	return false
}

// SetServiceAccount gets a reference to the given ControllersWhoAmIServiceAccount and assigns it to the ServiceAccount field.
func (o *ControllersWhoAmIResponse) SetServiceAccount(v ControllersWhoAmIServiceAccount) {
	o.ServiceAccount = &v
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *ControllersWhoAmIResponse) GetUser() ControllersWhoAmIUser {
	if o == nil || IsNil(o.User) {
		var ret ControllersWhoAmIUser
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ControllersWhoAmIResponse) GetUserOk() (*ControllersWhoAmIUser, bool) {
	if o == nil || IsNil(o.User) {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *ControllersWhoAmIResponse) HasUser() bool {
	if o != nil && !IsNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given ControllersWhoAmIUser and assigns it to the User field.
func (o *ControllersWhoAmIResponse) SetUser(v ControllersWhoAmIUser) {
	o.User = &v
}

func (o ControllersWhoAmIResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ControllersWhoAmIResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ServiceAccount) {
		toSerialize["service_account"] = o.ServiceAccount
	}
	if !IsNil(o.User) {
		toSerialize["user"] = o.User
	}
	return toSerialize, nil
}

type NullableControllersWhoAmIResponse struct {
	value *ControllersWhoAmIResponse
	isSet bool
}

func (v NullableControllersWhoAmIResponse) Get() *ControllersWhoAmIResponse {
	return v.value
}

func (v *NullableControllersWhoAmIResponse) Set(val *ControllersWhoAmIResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableControllersWhoAmIResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableControllersWhoAmIResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableControllersWhoAmIResponse(val *ControllersWhoAmIResponse) *NullableControllersWhoAmIResponse {
	return &NullableControllersWhoAmIResponse{value: val, isSet: true}
}

func (v NullableControllersWhoAmIResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableControllersWhoAmIResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


