name: Security Scan CI

on:
  pull_request:
  push:
    branches:
    - 'main'

jobs:
  security:
    uses: portworx/devsecops-github-actions/.github/workflows/security-golang.yml@master
    secrets: inherit